server:
  port: 8001

#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
#  type-aliases-package: com.jqc.springcloud.entities # 所有Entity别名类所在包
#  mapper-locations:
#    - classpath:mybatis/mapper/**/*.xml  # mapper映射文件

spring:
  application:
    name: goods
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    #    driver-class-name: org.gjt.mm.mysql.Driver # mysql驱动包
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://localhost:3306/testmybatisplus?useAffectedRows=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5 # 数据库连接池的最小连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 #最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间
  freemarker:
    template-loader-path:
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 1043888219@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: snqtadpkkcbybeic
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7002/eureka
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  instance: #主机映射名称修改
#    instance-id: microservice-dept8001
#    prefer-ip-address: true #访问路径左下角可以显示IP
#info:
#  app.name: jqc-microservicecloud
#  compancy.name: www.jqc.com
#  bulid.artifactId: ${project.artifactId}
#  bulid.version: ${project.version}
swagger:
  enabled: true